### ISSUE TITLE
Can't get address to show in admin

### ISSUE THREAD

**Issue by yatahaze** [furious-luke/django-address#92] opened 2020-01-15 20:20 UTC
When I use an autocomplete (or even just type anything into the address box) the resulting display in the admin is "None" when editable and "-" when readonly. Is there something I'm doing wrong?

**Comment by banagale** [comment] 2020-04-10 13:33
@yatahaze, @jerinpetergeorge. Did you find a resolution for this issue?

**Comment by banagale** [comment] 2020-04-10 13:47
I believe this is a duplicate of #89. Can someone please confirm this?

**Comment by timjonez** [comment] 2020-04-15 02:56
Hey,
I was having the same problem( it sounds like at least). For me it was two issues: 
1. I had the wrong google api enabled
2. Changed None to  ' ' as specified in #89 
So yes I believe it is duplicate

**Comment by banagale** [comment] 2020-04-20 03:56
@timjonez Thank you for that closing this as a duplicate.

**Closed by banagale** 2020-04-20 03:56 UTC
Labels: Duplicate
