### ISSUE TITLE
no completion of address 

### ISSUE THREAD

**Issue by k0ssi** [furious-luke/django-address#26] opened 2015-12-14 13:23 UTC
Django version: 1.8
django-address 0.1.3

after adding AddressField to my model and create migrations there is no address completion within admin menu. Entered address will be saved as raw within an new address object without any other data.

**Comment by k0ssi** [comment] 2015-12-22 13:53
i tested older versions of "django-address" going step by step backward within commits.Last working commit for me is 1fb1ab76e777e6b80e01359d75bc32524d50105a 

im using django 1.8 on Debian 7.8 
tested with Chrome Version 47 and Firefox 42

**Comment by banagale** [comment] 2020-04-19 15:14
Thank you for the report. I believe this is a duplicate of #89.

**Closed by banagale** 2020-04-19 15:14 UTC
Labels: Duplicate
