### ISSUE TITLE
Adjust the placement of Google map error icon on a admin form field

### ISSUE THREAD

**Issue by TheLazzziest** [furious-luke/django-address#107] opened 2020-05-17 09:40 UTC
It just overlaps on a input tag. [Preview](https://i.imgur.com/f2BSQXb.png)

**Comment by banagale** [comment] 2020-05-17 13:35
Thanks for pointing this out. I've added this to our next triage milestone for validation and fix.

**Comment by banagale** [comment] 2020-06-23 15:25
Possible duplicate of #79.

**Comment by banagale** [comment] 2020-06-28 18:59
This wasn't a duplicate, but the source issue describing the fix handled by #79.

#79 is now merged. Thanks @TheLazzziest for the initial report.

**Closed by banagale** 2020-06-28 18:59 UTC
Labels: Bug, Normal
