### ISSUE TITLE
DataError on saving with some addresses

### ISSUE THREAD

**Issue by Kmaschta** [furious-luke/django-address#22] opened 2015-08-19 14:32 UTC
Hi,

When I create some addresses like `28 Rue de Phalsbourg` (France), the State object creation raise a DataError, like this

![Error](http://image.noelshack.com/fichiers/2015/34/1439994673-dataerror-at-profil.png)

**Comment by gumaerc** [comment] 2015-08-19 18:56
This has to do with the character limit on the state field being 3 characters.  In certain cases states will come back with the same name in the "long_name" and "short_name" property.  I discovered this and tried out expanding the character limit on the state code field and it fixed the error, but I'm not sure this is the solution we want.  Maybe we want to ignore the field if the value that comes back from Google is longer than 3 characters?

**Comment by furious-luke** [comment] 2015-08-20 00:31
Hi there,

Indeed, you're correct in your assessment; extending the state code length allows the value to be stored. However, I think ignoring the value makes more sense, as we already have the long name stored, and if there is no shorter code to represent it then we shouldn't need to store anything.

I've modified the code to check for duplicate codes and ignore them. However an exception will still be raised if the short code is longer than the maximum allowed length and is not a duplicate of the longer name.

I've added some new unit-tests and checked that the address mentioned goes through correctly. Please let me know if it doesn't work for you.

Cheers,
Luke

**Comment by gumaerc** [comment] 2015-08-20 02:58
That makes sense.  Thank you!

**Comment by furious-luke** [comment] 2015-08-20 03:03
You're very welcome, thanks for the input!

**Closed** 2015-11-03 01:50 UTC
