### ISSUE TITLE
Improper value rendered in the template

### ISSUE THREAD

**Issue by macmichael01** [furious-luke/django-address#48] opened 2016-05-15 00:01 UTC
I would like to get the value from a form field via the template such as 'San Francisco, CA, USA' like so:

`{{ form.address_field.value }}`

Instead I receive a number which I am assuming is the PK to a referencing table. Is this a bug or is there another way to reference this value?

**Comment by furious-luke** [comment] 2016-05-15 04:08
Hi there, have you tried rendering the field like this: `{{ form.address_field }}`? [The Django documentation](https://docs.djangoproject.com/en/1.9/topics/forms/#rendering-fields-manually) recommends rendering fields without `.value`.

**Comment by furious-luke** [comment] 2016-05-15 04:25
Oh hang, on I understand what you're after; you probably want just the value without the input tags in order to do some custom rendering. Yep, you'll be getting the PK because the `AddressField` is inherits directly from `ForeignKey`. Give me a minute and I'll hunt down a way to get the rendered string instead of the PK.

**Comment by furious-luke** [comment] 2016-05-15 04:40
Okay, so, after a little investigation it seems getting the PK back from a call to value is the expected behaviour. This makes sense, as the value in the case of models is the PK (there could be a number of models with the same string representation but different PKs).

To get a string representation of the address from the form field you can access the model object from the initial data: `{{ form.initial.address_field }}`. I'm not sure if this is the best way to do it, but it should work.

**Comment by macmichael01** [comment] 2016-05-15 18:01
I tried your suggestion but it still returns a pk.

**Comment by furious-luke** [comment] 2016-05-16 00:05
I've modified the example site in `example_site` to show you a working implementation of my suggestion. I'm guessing you might be setting the initial value to a PK instead of an `Address` object if it still gives you a PK from the initial dictionary.

In any case, as I said, getting a PK from `value` is expected behaviour from Django's `ModelChoiceField`. There are other ways of getting a string representation of the field, [see here for an example](http://stackoverflow.com/questions/16042734/django-forms-get-selected-item-from-modelchoicefield). As such, this is not actually an issue with `django-address`, so I'll close this issue.

**Closed by furious-luke** 2016-05-16 00:05 UTC
