### ISSUE TITLE
How to get a integrate correctly in my form

### ISSUE THREAD

**Issue by janssja** [furious-luke/django-address#62] opened 2016-12-12 08:57 UTC
Hi,
I'm kind of new in the Django community and I am looking to integrate django-address in my code. Although the address firld is visible it seems to contain no auto-complete and once an address is entered it is not saved in my database. It al works fine when I use the admin. Can you help me?
Regards,
Jackie

In my models.py I have:
```
from address.models import AddressField


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = AddressField(blank=True, null=True)
```
In my forms.py I have:
```
class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        address = AddressField
        fields = ('address', 'birth_date', 'bio', 'active', 'other_details' )
```
In my views.py:
```
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        member_form = MemberForm(request.POST, instance=request.user.member)
        if user_form.is_valid():
            try:
                user_form.save()
                member_form.save()
            except:
                pass
        # else:
        #     messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        member_form = MemberForm(instance=request.user.member)
    return render(request, 'profile.html', {
        'user_form': user_form,
        'member_form': member_form,
    })
```
and finally my profile.html:
```
               <form method="post">
                  {% csrf_token %}
                  {{ user_form|crispy }}
                  {{ member_form|crispy }}
                  <button class="btn btn-default" type="submit">Save changes</button>
                </form>
```

**Comment by fatk1d** [comment] 2017-12-22 16:41
I ran into a similar issue and spent two days trying to resolve it.  I finally resolved it and I believe the ultimate cause of my particular issue was that I wasn't loading the static files in my own application correctly.  The static files in the django-address application were being loaded just fine when the {{forms.media}} template tag was encountered but the actual javascript libraries in my own project (geocomplete, query) weren't being loaded correctly.  After executing 'runserver', hit it with a web browser and make sure that these static components are being loaded correctly.

Of course, I realize my response is over a year old since you posted your question but others might benefit from 16+ hours blown trying to troubleshoot this issue.

**Comment by bansalnvn** [comment] 2019-03-17 11:17
Hi, When I am trying to use {{ form.address }} in my view template file. It is generating the hidden text fields for all the address attributes.
```

<input type="text" name="address" class="address" placeholder="None" required id="id_address">
--
  | <div id="address_components">
  | <input type="hidden" name="address_country" data-geo="country" value="" />
  | <input type="hidden" name="address_country_code" data-geo="country_short" value="" />
  | <input type="hidden" name="address_locality" data-geo="locality" value="" />
  | <input type="hidden" name="address_sublocality" data-geo="sublocality" value="" />
  | <input type="hidden" name="address_postal_code" data-geo="postal_code" value="" />
  | <input type="hidden" name="address_route" data-geo="route" value="" />
  | <input type="hidden" name="address_street_number" data-geo="street_number" value="" />
  | <input type="hidden" name="address_state" data-geo="administrative_area_level_1" value="" />
  | <input type="hidden" name="address_state_code" data-geo="administrative_area_level_1_short" value="" />
  | <input type="hidden" name="address_formatted" data-geo="formatted_address" value="" />
  | <input type="hidden" name="address_latitude" data-geo="lat" value="" />
  | <input type="hidden" name="address_longitude" data-geo="lng" value="" />
  | </div>
```

Is it how it is supposed to work ?

**Comment by gouravsinha05** [comment] 2019-12-04 08:42
Hey Thanks 
Really helped me, small change there is a issue (maybe because of latest version ) 

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        address = AddressField
        **fields = ('address', 'birth_date', 'bio', 'active', 'other_details' )**
is now 


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        address = AddressField
        **fields = ['address', 'birth_date', 'bio', 'active', 'other_details' ]**

**Comment by banagale** [comment] 2020-04-20 03:50
Closing as a duplicate of #92.

**Closed by banagale** 2020-04-20 03:50 UTC
